# Generated by Django 5.2.7 on 2025-10-29 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lancamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("breve", "Breve Lançamento"),
                            ("obras", "Em Obras"),
                            ("pronto", "Pronto para Morar"),
                        ],
                        default="breve",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                (
                    "descricao_curta",
                    models.CharField(
                        help_text="Chamada rápida exibida nos cards da home",
                        max_length=250,
                        verbose_name="Descrição Curta",
                    ),
                ),
                (
                    "descricao_completa",
                    models.TextField(
                        help_text="Texto detalhado para a página de detalhes",
                        verbose_name="Descrição Completa",
                    ),
                ),
                (
                    "imagem_principal",
                    models.ImageField(
                        help_text="Banner ou foto de capa",
                        upload_to="lancamentos/",
                        verbose_name="Imagem Principal",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Define se o lançamento aparece no site",
                        verbose_name="Ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento",
                "verbose_name_plural": "Lançamentos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="GaleriaImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="lancamentos/galeria/", verbose_name="Imagem"
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda"
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(
                        default=0,
                        help_text="Define a ordem de exibição das imagens",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria_imagens",
                        to="core.lancamento",
                        verbose_name="Lançamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da Galeria",
                "verbose_name_plural": "Imagens da Galeria",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
