# Generated by Django 5.2.3 on 2025-10-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diferencial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "descricao",
                    models.TextField(
                        help_text="Texto explicativo do diferencial",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        help_text="Imagem ilustrativa do diferencial",
                        upload_to="diferenciais/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(
                        default=0,
                        help_text="Define a ordem de exibição",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Define se o diferencial aparece no site",
                        verbose_name="Ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diferencial",
                "verbose_name_plural": "Diferenciais",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
