# Generated by Django 5.2.3 on 2025-10-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_diferencial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Investimento Inteligente em Imóveis",
                        max_length=200,
                        verbose_name="Título Principal",
                    ),
                ),
                (
                    "subtitulo",
                    models.CharField(
                        default="Transforme seu capital em patrimônio com segurança e rentabilidade",
                        max_length=300,
                        verbose_name="Subtítulo",
                    ),
                ),
                (
                    "texto_botao",
                    models.CharField(
                        default="Consultoria Especializada",
                        max_length=100,
                        verbose_name="Texto do Botão",
                    ),
                ),
                (
                    "imagem_fundo",
                    models.ImageField(
                        help_text="Imagem de fundo da seção principal (recomendado: 1920x1080px)",
                        upload_to="hero/",
                        verbose_name="Imagem de Fundo",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Apenas uma Hero Section pode estar ativa por vez",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
                "ordering": ["-ativo", "-data_atualizacao"],
            },
        ),
        migrations.CreateModel(
            name="SobreSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Nossa História",
                        max_length=200,
                        verbose_name="Título da Seção",
                    ),
                ),
                (
                    "nome_fundadora",
                    models.CharField(
                        default="Camilla Daianne",
                        max_length=100,
                        verbose_name="Nome da Fundadora",
                    ),
                ),
                (
                    "texto_fundadora",
                    models.TextField(
                        help_text="Parágrafo sobre Camilla Daianne",
                        verbose_name="Texto sobre a Fundadora",
                    ),
                ),
                (
                    "foto_fundadora",
                    models.ImageField(
                        help_text="Foto de Camilla (recomendado: 500x500px)",
                        upload_to="sobre/",
                        verbose_name="Foto da Fundadora",
                    ),
                ),
                (
                    "nome_fundador",
                    models.CharField(
                        default="Marlon Deivison",
                        max_length=100,
                        verbose_name="Nome do Fundador",
                    ),
                ),
                (
                    "texto_fundador",
                    models.TextField(
                        help_text="Parágrafo sobre Marlon Deivison",
                        verbose_name="Texto sobre o Fundador",
                    ),
                ),
                (
                    "foto_fundador",
                    models.ImageField(
                        help_text="Foto de Marlon (recomendado: 500x500px)",
                        upload_to="sobre/",
                        verbose_name="Foto do Fundador",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Apenas uma Seção Sobre pode estar ativa por vez",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção Sobre (Nossa História)",
                "verbose_name_plural": "Seções Sobre (Nossa História)",
                "ordering": ["-ativo", "-data_atualizacao"],
            },
        ),
    ]
