# Generated by Django 5.2.3 on 2025-10-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_herosection_sobresection"),
    ]

    operations = [
        migrations.AddField(
            model_name="diferencial",
            name="link_botao",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL para onde o botão irá redirecionar",
                verbose_name="Link do Botão",
            ),
        ),
        migrations.AddField(
            model_name="diferencial",
            name="texto_botao",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Texto exibido no botão do diferencial",
                max_length=100,
                verbose_name="Texto do Botão",
            ),
        ),
    ]
