# Generated by Django 5.2.3 on 2025-10-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_diferencial_link_botao_diferencial_texto_botao"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentCTASection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Sua próxima grande oportunidade",
                        max_length=200,
                        verbose_name="Título Principal",
                    ),
                ),
                (
                    "subtitulo",
                    models.TextField(
                        default="Está pronto para transformar seu capital em um investimento imobiliário inteligente e altamente lucrativo? Nossa equipe está pronta para apresentar as melhores estratégias e oportunidades, baseadas em nossa profunda análise de mercado.",
                        verbose_name="Subtítulo",
                    ),
                ),
                (
                    "imagem_fundo",
                    models.ImageField(
                        help_text="Imagem de fundo da seção (recomendado: 1920x800px)",
                        upload_to="cta_investimento/",
                        verbose_name="Imagem de Fundo",
                    ),
                ),
                (
                    "texto_botao",
                    models.CharField(
                        default="Receber Análise Completa de Investimentos",
                        max_length=100,
                        verbose_name="Texto do Botão",
                    ),
                ),
                (
                    "link_botao",
                    models.URLField(
                        default="https://api.whatsapp.com/send?phone=5577999106220&text=Ol%C3%A1!%20Gostaria%20de%20receber%20a%20An%C3%A1lise%20Completa%20de%20Investimentos.",
                        verbose_name="Link do Botão",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Apenas uma CTA pode estar ativa por vez",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção CTA Investimento",
                "verbose_name_plural": "Seções CTA Investimento",
                "ordering": ["-ativo", "-data_atualizacao"],
            },
        ),
    ]
