# Generated by Django 5.2.3 on 2025-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_investmentctasection"),
    ]

    operations = [
        migrations.AddField(
            model_name="galeriaimagem",
            name="destaque_home",
            field=models.BooleanField(
                default=False,
                help_text="Marque para exibir esta imagem na home. Máximo de 3 por imóvel.",
                verbose_name="Exibir na página inicial?",
            ),
        ),
    ]
