# Generated by Django 5.2.3 on 2025-10-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_galeriaimagem_destaque_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galeriaimagem",
            name="destaque_home",
            field=models.BooleanField(
                default=False,
                help_text="Marque para exibir esta imagem na página inicial",
                verbose_name="Exibir na página inicial?",
            ),
        ),
    ]
