# Generated by Django 5.2.7 on 2025-11-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_galeriaimagem_destaque_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="Depoimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Cliente"),
                ),
                (
                    "foto",
                    models.ImageField(
                        help_text="Foto do cliente (recomendado: 300x300px)",
                        upload_to="depoimentos/",
                        verbose_name="Foto do Cliente",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Texto do depoimento do cliente",
                        verbose_name="Depoimento",
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(
                        default=0,
                        help_text="Define a ordem de exibição dos depoimentos",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Define se o depoimento aparece no site",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Depoimento",
                "verbose_name_plural": "Depoimentos",
                "ordering": ["ordem", "-data_criacao"],
            },
        ),
    ]
