# Generated by Django 5.2.7 on 2025-11-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_depoimento"),
    ]

    operations = [
        migrations.CreateModel(
            name="LancamentosHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Nossos Empreendimentos",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "subtitulo",
                    models.CharField(
                        default="Conheça os lançamentos e oportunidades disponíveis",
                        max_length=300,
                        verbose_name="Subtítulo",
                    ),
                ),
                (
                    "imagem_fundo",
                    models.ImageField(
                        help_text="Imagem de fundo da seção hero (recomendado: 1920x600px)",
                        upload_to="hero/",
                        verbose_name="Imagem de Fundo",
                    ),
                ),
                (
                    "opacidade",
                    models.IntegerField(
                        default=60,
                        help_text="Opacidade da camada escura sobre a imagem (0-100)",
                        verbose_name="Opacidade do Overlay (%)",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Apenas um hero pode estar ativo por vez",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero da Página de Lançamentos",
                "verbose_name_plural": "Heroes da Página de Lançamentos",
                "ordering": ["-ativo", "-data_atualizacao"],
            },
        ),
    ]
