# Generated by Django 5.2.3 on 2025-11-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_lancamentoshero"),
    ]

    operations = [
        migrations.CreateModel(
            name="LancamentosVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Conheça Nossos Empreendimentos",
                        max_length=200,
                        verbose_name="Título da Seção",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="Cole o link completo do vídeo do YouTube (ex: https://www.youtube.com/watch?v=pzfQS88dgJg)",
                        verbose_name="Link do Vídeo do YouTube",
                    ),
                ),
                (
                    "texto_botao",
                    models.CharField(
                        default="Falar com Especialista",
                        max_length=100,
                        verbose_name="Texto do Botão WhatsApp",
                    ),
                ),
                (
                    "link_whatsapp",
                    models.URLField(
                        default="https://wa.me/5577999106220?text=Ol%C3%A1%2C%20gostaria%20de%20saber%20mais%20sobre%20os%20lan%C3%A7amentos.",
                        help_text="Link do WhatsApp com mensagem pré-definida",
                        verbose_name="Link do WhatsApp",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Apenas um vídeo pode estar ativo por vez",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "autoplay",
                    models.BooleanField(
                        default=True,
                        help_text="Iniciar vídeo automaticamente quando entrar na página",
                        verbose_name="Reprodução Automática",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vídeo da Página de Lançamentos",
                "verbose_name_plural": "Vídeos da Página de Lançamentos",
                "ordering": ["-ativo", "-data_atualizacao"],
            },
        ),
        migrations.AlterField(
            model_name="lancamentoshero",
            name="imagem_fundo",
            field=models.ImageField(
                help_text="Imagem de fundo da seção hero (recomendado: 1920x1080px)",
                upload_to="hero/",
                verbose_name="Imagem de Fundo",
            ),
        ),
        migrations.AlterField(
            model_name="lancamentoshero",
            name="opacidade",
            field=models.IntegerField(
                default=60,
                help_text="Opacidade da camada BRANCA sobre a imagem (0=transparente, 100=branco total)",
                verbose_name="Opacidade do Overlay Branco (%)",
            ),
        ),
    ]
