# Generated by Django 5.2.3 on 2025-11-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_lancamentosvideo_alter_lancamentoshero_imagem_fundo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depoimento",
            options={
                "ordering": ["ordem", "-data_criacao"],
                "verbose_name": "Depoimento de Cliente",
                "verbose_name_plural": "Depoimentos de Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="diferencial",
            options={
                "ordering": ["ordem", "id"],
                "verbose_name": "Diferencial da Empresa",
                "verbose_name_plural": "Diferenciais da Empresa",
            },
        ),
        migrations.AlterModelOptions(
            name="galeriaimagem",
            options={
                "ordering": ["ordem", "id"],
                "verbose_name": "Imagem do Empreendimento",
                "verbose_name_plural": "Imagens dos Empreendimentos",
            },
        ),
        migrations.AlterModelOptions(
            name="herosection",
            options={
                "ordering": ["-ativo", "-data_atualizacao"],
                "verbose_name": "Banner Principal (Home)",
                "verbose_name_plural": "Banners Principais (Home)",
            },
        ),
        migrations.AlterModelOptions(
            name="investmentctasection",
            options={
                "ordering": ["-ativo", "-data_atualizacao"],
                "verbose_name": "Chamada para Investimento (Home)",
                "verbose_name_plural": "Chamadas para Investimento (Home)",
            },
        ),
        migrations.AlterModelOptions(
            name="lancamento",
            options={
                "ordering": ["-data_criacao"],
                "verbose_name": "Empreendimento / Lançamento",
                "verbose_name_plural": "Empreendimentos / Lançamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="lancamentoshero",
            options={
                "ordering": ["-ativo", "-data_atualizacao"],
                "verbose_name": "Banner da Página Lançamentos",
                "verbose_name_plural": "Banners da Página Lançamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="lancamentosvideo",
            options={
                "ordering": ["-ativo", "-data_atualizacao"],
                "verbose_name": "Vídeo da Página Home",
                "verbose_name_plural": "Vídeos da Página Home",
            },
        ),
        migrations.AlterModelOptions(
            name="sobresection",
            options={
                "ordering": ["-ativo", "-data_atualizacao"],
                "verbose_name": "Nossa História (Home)",
                "verbose_name_plural": "Nossa História (Home)",
            },
        ),
        migrations.AlterField(
            model_name="lancamentosvideo",
            name="titulo",
            field=models.CharField(
                blank=True,
                default="Conheça Nossos Empreendimentos",
                max_length=200,
                verbose_name="Título da Seção",
            ),
        ),
    ]
