# Generated by Django 5.2.3 on 2025-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_depoimento_options_alter_diferencial_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentosvideo',
            name='titulo',
            field=models.CharField(blank=True, default='Conheça Nossos Empreendimentos', max_length=200, verbose_name='Título da Seção'),
        ),
    ]
