# Generated by Django 5.2.3 on 2025-11-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_ajusta_titulo_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lancamentosvideo",
            name="video_url",
        ),
        migrations.AddField(
            model_name="lancamentosvideo",
            name="video_arquivo",
            field=models.FileField(
                blank=True,
                help_text="Formatos suportados: MP4, WebM, OGG, MOV",
                null=True,
                upload_to="videos/",
                verbose_name="Arquivo de Vídeo",
            ),
        ),
    ]
