# Generated by Django 5.2.3 on 2025-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_altera_video_para_arquivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="texto_destaque",
            field=models.CharField(
                blank=True,
                help_text='Texto em destaque entre o título e subtítulo (ex: "DE SUCESSO")',
                max_length=100,
                verbose_name="Texto de Destaque",
            ),
        ),
    ]
