[program:standart7]
command=/var/www/standart7/venv/bin/gunicorn standart7.wsgi:application --bind 127.0.0.1:8000 --workers 3 --timeout 120
directory=/var/www/standart7
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/standart7/logs/gunicorn.log
stderr_logfile=/var/www/standart7/logs/gunicorn_error.log
environment=PATH="/var/www/standart7/venv/bin"
